# Generated by Django 5.0 on 2024-01-01 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsRepliedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reddit_id', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Comments Replied To',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('amount_in_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_unpaid', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('original_thread', models.URLField(blank=True, max_length=1000, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_id', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedditUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('borrower_pending_loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('borrower_completed_loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('borrower_pending_loan_count', models.IntegerField(default=0)),
                ('borrower_completed_loan_count', models.IntegerField(default=0)),
                ('borrower_repayment_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lender_pending_loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lender_completed_loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lender_pending_loan_count', models.IntegerField(default=0)),
                ('lender_completed_loan_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('has_unpaid_loan', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loanmanager.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_loans', to='loanmanager.reddituser'),
        ),
        migrations.AddField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent_loans', to='loanmanager.reddituser'),
        ),
    ]
