# Generated by Django 5.0 on 2023-12-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='comment_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
