# Generated by Django 5.0 on 2024-01-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='is_mod',
            field=models.BooleanField(default=False),
        ),
    ]
