# Generated by Django 5.0 on 2023-12-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0002_loan_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsRepliedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reddit_id', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
