# Generated by Django 4.1 on 2024-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0003_currencyconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='lender_unpaid_loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='lender_unpaid_loan_count',
            field=models.IntegerField(default=0),
        ),
    ]
