# Generated by Django 5.0 on 2023-12-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0003_commentsrepliedto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsrepliedto',
            options={'verbose_name_plural': 'Comments Replied To'},
        ),
        migrations.AddField(
            model_name='reddituser',
            name='borrower_completed_loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='borrower_completed_loan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='borrower_pending_loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='borrower_pending_loan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='borrower_repayment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='lender_completed_loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='lender_completed_loan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='lender_pending_loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='lender_pending_loan_count',
            field=models.IntegerField(default=0),
        ),
    ]
